import {
  PhotoAdjustments,
  Preset,
  HSLState,
  ColorGradingState,
  ToneCurveState,
  CropState,
} from '../types/editor';

export const createDefaultHSLState = (): HSLState => ({
  red: { hue: 0, saturation: 0, luminance: 0 },
  orange: { hue: 0, saturation: 0, luminance: 0 },
  yellow: { hue: 0, saturation: 0, luminance: 0 },
  green: { hue: 0, saturation: 0, luminance: 0 },
  aqua: { hue: 0, saturation: 0, luminance: 0 },
  blue: { hue: 0, saturation: 0, luminance: 0 },
  purple: { hue: 0, saturation: 0, luminance: 0 },
  magenta: { hue: 0, saturation: 0, luminance: 0 },
});

export const createDefaultColorGradingState = (): ColorGradingState => ({
  shadows: { hue: 0, saturation: 0, luminance: 0 },
  midtones: { hue: 0, saturation: 0, luminance: 0 },
  highlights: { hue: 0, saturation: 0, luminance: 0 },
  blending: 50,
  balance: 0,
});

export const createDefaultToneCurveState = (): ToneCurveState => ({
  master: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  red: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  green: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
  blue: [{ x: 0, y: 0 }, { x: 255, y: 255 }],
});

export const createDefaultCropState = (): CropState => ({
  aspectRatio: 'free',
  rotation: 0,
  flipH: false,
  flipV: false,
  x: 0,
  y: 0,
  width: 1,
  height: 1,
});

export const createDefaultAdjustments = (): PhotoAdjustments => ({
  exposure: 0,
  contrast: 0,
  highlights: 0,
  shadows: 0,
  whites: 0,
  blacks: 0,

  temp: 5500,
  tint: 0,
  vibrance: 0,
  saturation: 0,

  hsl: createDefaultHSLState(),
  colorGrading: createDefaultColorGradingState(),
  toneCurve: createDefaultToneCurveState(),

  clarity: 0,
  texture: 0,
  dehaze: 0,
  vignette: 0,
  sharpening: 15,
  grain: 0,

  crop: createDefaultCropState(),
});

/**
 * Non-destructive preset intensity blending function.
 * Linearly interpolates preset settings with base adjustments according to intensity (0-100%).
 */
export function blendPresetAdjustments(
  baseAdj: PhotoAdjustments,
  presetAdj: Partial<PhotoAdjustments>,
  intensityPercent: number
): PhotoAdjustments {
  const factor = Math.max(0, Math.min(100, intensityPercent)) / 100;
  const lerp = (base: number, target: number) => base + (target - base) * factor;

  const result: PhotoAdjustments = { ...baseAdj };

  if (presetAdj.exposure !== undefined) result.exposure = lerp(baseAdj.exposure, presetAdj.exposure);
  if (presetAdj.contrast !== undefined) result.contrast = lerp(baseAdj.contrast, presetAdj.contrast);
  if (presetAdj.highlights !== undefined) result.highlights = lerp(baseAdj.highlights, presetAdj.highlights);
  if (presetAdj.shadows !== undefined) result.shadows = lerp(baseAdj.shadows, presetAdj.shadows);
  if (presetAdj.whites !== undefined) result.whites = lerp(baseAdj.whites, presetAdj.whites);
  if (presetAdj.blacks !== undefined) result.blacks = lerp(baseAdj.blacks, presetAdj.blacks);

  if (presetAdj.temp !== undefined) result.temp = lerp(baseAdj.temp, presetAdj.temp);
  if (presetAdj.tint !== undefined) result.tint = lerp(baseAdj.tint, presetAdj.tint);
  if (presetAdj.vibrance !== undefined) result.vibrance = lerp(baseAdj.vibrance, presetAdj.vibrance);
  if (presetAdj.saturation !== undefined) result.saturation = lerp(baseAdj.saturation, presetAdj.saturation);

  if (presetAdj.clarity !== undefined) result.clarity = lerp(baseAdj.clarity, presetAdj.clarity);
  if (presetAdj.texture !== undefined) result.texture = lerp(baseAdj.texture, presetAdj.texture);
  if (presetAdj.dehaze !== undefined) result.dehaze = lerp(baseAdj.dehaze, presetAdj.dehaze);
  if (presetAdj.vignette !== undefined) result.vignette = lerp(baseAdj.vignette, presetAdj.vignette);
  if (presetAdj.sharpening !== undefined) result.sharpening = lerp(baseAdj.sharpening, presetAdj.sharpening);
  if (presetAdj.grain !== undefined) result.grain = lerp(baseAdj.grain, presetAdj.grain);

  if (presetAdj.hsl) {
    const blendedHSL = { ...baseAdj.hsl };
    const channels = ['red', 'orange', 'yellow', 'green', 'aqua', 'blue', 'purple', 'magenta'] as const;
    channels.forEach((ch) => {
      const pCh = presetAdj.hsl?.[ch];
      const bCh = baseAdj.hsl[ch];
      if (pCh) {
        blendedHSL[ch] = {
          hue: lerp(bCh.hue, pCh.hue),
          saturation: lerp(bCh.saturation, pCh.saturation),
          luminance: lerp(bCh.luminance, pCh.luminance),
        };
      }
    });
    result.hsl = blendedHSL;
  }

  if (presetAdj.colorGrading) {
    const pCG = presetAdj.colorGrading;
    const bCG = baseAdj.colorGrading;
    result.colorGrading = {
      shadows: pCG.shadows
        ? {
            hue: lerp(bCG.shadows.hue, pCG.shadows.hue),
            saturation: lerp(bCG.shadows.saturation, pCG.shadows.saturation),
            luminance: lerp(bCG.shadows.luminance, pCG.shadows.luminance),
          }
        : bCG.shadows,
      midtones: pCG.midtones
        ? {
            hue: lerp(bCG.midtones.hue, pCG.midtones.hue),
            saturation: lerp(bCG.midtones.saturation, pCG.midtones.saturation),
            luminance: lerp(bCG.midtones.luminance, pCG.midtones.luminance),
          }
        : bCG.midtones,
      highlights: pCG.highlights
        ? {
            hue: lerp(bCG.highlights.hue, pCG.highlights.hue),
            saturation: lerp(bCG.highlights.saturation, pCG.highlights.saturation),
            luminance: lerp(bCG.highlights.luminance, pCG.highlights.luminance),
          }
        : bCG.highlights,
      blending: pCG.blending !== undefined ? lerp(bCG.blending, pCG.blending) : bCG.blending,
      balance: pCG.balance !== undefined ? lerp(bCG.balance, pCG.balance) : bCG.balance,
    };
  }

  if (presetAdj.toneCurve && factor >= 0.2) {
    result.toneCurve = presetAdj.toneCurve as ToneCurveState;
  }

  return result;
}

export const BUILT_IN_PRESETS: Preset[] = [
  {
    id: 'preset-original',
    name: 'Reset / Original',
    category: 'Built-in',
    description: 'Revert all controls to initial neutral balance.',
    adjustments: createDefaultAdjustments(),
  },

  // === ICONIC CINEMATIC & FILM MOVIE LOOKS (12 Presets) ===
  {
    id: 'preset-dune-arrakis',
    name: 'Dune (Arrakis Warmth)',
    category: 'Cinematic & Film',
    description: 'Desaturated high keys, warm sandy gold highlights, muted slate blues, lifted shadows.',
    adjustments: {
      exposure: 0.15,
      contrast: 12,
      highlights: -20,
      shadows: 30,
      whites: 10,
      blacks: 22,
      temp: 6700,
      tint: 8,
      vibrance: -30,
      saturation: -25,
      clarity: 12,
      texture: 8,
      grain: 15,
      vignette: -15,
      colorGrading: {
        shadows: { hue: 210, saturation: 18, luminance: 5 },
        midtones: { hue: 40, saturation: 22, luminance: 0 },
        highlights: { hue: 45, saturation: 38, luminance: 8 },
        blending: 60,
        balance: 10,
      },
    },
  },
  {
    id: 'preset-bladerunner-2049',
    name: 'Blade Runner 2049 (Cyberpunk)',
    category: 'Cinematic & Film',
    description: 'Deep teal shadows, rich magenta and cyan highlights, punchy cyberpunk contrast.',
    adjustments: {
      exposure: 0.05,
      contrast: 35,
      highlights: -15,
      shadows: -10,
      whites: 25,
      blacks: -25,
      temp: 4800,
      tint: -15,
      vibrance: 38,
      saturation: 18,
      clarity: 25,
      texture: 15,
      dehaze: 15,
      vignette: -30,
      colorGrading: {
        shadows: { hue: 190, saturation: 45, luminance: -10 },
        midtones: { hue: 25, saturation: 18, luminance: 0 },
        highlights: { hue: 325, saturation: 40, luminance: 10 },
        blending: 65,
        balance: -12,
      },
    },
  },
  {
    id: 'preset-oppenheimer-bw',
    name: 'Oppenheimer (Silver Noir)',
    category: 'Cinematic & Film',
    description: 'Intense, high-contrast B&W with silver midtones, crisp highlights, and crushed blacks.',
    adjustments: {
      exposure: 0.1,
      contrast: 42,
      highlights: -20,
      shadows: -18,
      whites: 32,
      blacks: -35,
      temp: 5500,
      vibrance: -100,
      saturation: -100,
      clarity: 32,
      texture: 22,
      sharpening: 35,
      grain: 25,
      vignette: -20,
    },
  },
  {
    id: 'preset-oppenheimer-technicolor',
    name: 'Oppenheimer (1940s Technicolor)',
    category: 'Cinematic & Film',
    description: 'Warm 1940s Technicolor warmth with rich reds, creamy skin tones, and organic contrast.',
    adjustments: {
      exposure: 0.15,
      contrast: 20,
      highlights: -25,
      shadows: 20,
      whites: 12,
      blacks: -8,
      temp: 6200,
      tint: 12,
      vibrance: 25,
      saturation: 15,
      clarity: 8,
      grain: 18,
      vignette: -12,
      colorGrading: {
        shadows: { hue: 30, saturation: 18, luminance: 0 },
        midtones: { hue: 38, saturation: 15, luminance: 0 },
        highlights: { hue: 48, saturation: 28, luminance: 5 },
        blending: 50,
        balance: 5,
      },
    },
  },
  {
    id: 'preset-wes-anderson',
    name: 'Wes Anderson (Pastel Symmetry)',
    category: 'Cinematic & Film',
    description: 'Vibrant pastel yellow/pink color wash, desaturated deep shadows, bright symmetrical midtones.',
    adjustments: {
      exposure: 0.2,
      contrast: -8,
      highlights: -35,
      shadows: 35,
      whites: 15,
      blacks: 18,
      temp: 6100,
      tint: 18,
      vibrance: 28,
      saturation: 10,
      clarity: -10,
      texture: -5,
      vignette: -8,
      colorGrading: {
        shadows: { hue: 340, saturation: 15, luminance: 10 },
        midtones: { hue: 50, saturation: 25, luminance: 5 },
        highlights: { hue: 45, saturation: 35, luminance: 10 },
        blending: 55,
        balance: 8,
      },
    },
  },
  {
    id: 'preset-matrix-green-cinematic',
    name: 'The Matrix (Green Tint)',
    category: 'Cinematic & Film',
    description: 'Classic late-90s sci-fi aesthetic—heavy green-tinted shadows with desaturated primaries.',
    adjustments: {
      exposure: -0.05,
      contrast: 32,
      highlights: -25,
      shadows: -12,
      whites: 15,
      blacks: -25,
      temp: 5000,
      tint: -38,
      vibrance: -35,
      saturation: -25,
      clarity: 24,
      texture: 15,
      dehaze: 12,
      vignette: -32,
      colorGrading: {
        shadows: { hue: 140, saturation: 42, luminance: -8 },
        midtones: { hue: 130, saturation: 25, luminance: 0 },
        highlights: { hue: 120, saturation: 20, luminance: 5 },
        blending: 60,
        balance: -15,
      },
    },
  },
  {
    id: 'preset-amelie-parisian',
    name: 'Amélie (Parisian Warmth)',
    category: 'Cinematic & Film',
    description: 'High-saturation warm greens, glowing gold/amber highlights, and vivid Parisian reds.',
    adjustments: {
      exposure: 0.15,
      contrast: 22,
      highlights: -20,
      shadows: 20,
      whites: 18,
      blacks: -10,
      temp: 6400,
      tint: -12,
      vibrance: 45,
      saturation: 22,
      clarity: 12,
      vignette: -18,
      colorGrading: {
        shadows: { hue: 135, saturation: 30, luminance: -2 },
        midtones: { hue: 42, saturation: 20, luminance: 0 },
        highlights: { hue: 48, saturation: 40, luminance: 10 },
        blending: 55,
        balance: 0,
      },
    },
  },
  {
    id: 'preset-euphoria-glow',
    name: 'Euphoria (Glow & Grain)',
    category: 'Cinematic & Film',
    description: 'Dreamy purple/magenta hues, soft glow contrast, lifted darks, and organic film grain.',
    adjustments: {
      exposure: 0.2,
      contrast: -12,
      highlights: -40,
      shadows: 38,
      whites: -10,
      blacks: 28,
      temp: 4500,
      tint: 35,
      vibrance: 50,
      saturation: 18,
      clarity: -18,
      texture: -10,
      grain: 35,
      vignette: -22,
      colorGrading: {
        shadows: { hue: 270, saturation: 38, luminance: 8 },
        midtones: { hue: 310, saturation: 22, luminance: 0 },
        highlights: { hue: 330, saturation: 35, luminance: 12 },
        blending: 60,
        balance: 5,
      },
    },
  },
  {
    id: 'preset-the-batman-noir',
    name: 'The Batman (Dark Knight)',
    category: 'Cinematic & Film',
    description: 'Ultra-low exposure, deep crushed blacks, subtle amber street-lamp highlights.',
    adjustments: {
      exposure: -0.45,
      contrast: 42,
      highlights: -15,
      shadows: -40,
      whites: 20,
      blacks: -50,
      temp: 5800,
      tint: 8,
      vibrance: -40,
      saturation: -30,
      clarity: 30,
      dehaze: 18,
      vignette: -48,
      grain: 22,
      colorGrading: {
        shadows: { hue: 220, saturation: 15, luminance: -15 },
        midtones: { hue: 30, saturation: 10, luminance: -5 },
        highlights: { hue: 38, saturation: 45, luminance: 15 },
        blending: 70,
        balance: -20,
      },
    },
  },
  {
    id: 'preset-lalaland-romance',
    name: 'La La Land (Twilight Romance)',
    category: 'Cinematic & Film',
    description: 'Vivid primaries, rich twilight purples, saturated deep blues, bright glowing highlights.',
    adjustments: {
      exposure: 0.15,
      contrast: 28,
      highlights: -15,
      shadows: 18,
      whites: 22,
      blacks: -15,
      temp: 4900,
      tint: 15,
      vibrance: 52,
      saturation: 28,
      clarity: 15,
      vignette: -15,
      colorGrading: {
        shadows: { hue: 260, saturation: 32, luminance: -5 },
        midtones: { hue: 280, saturation: 18, luminance: 0 },
        highlights: { hue: 45, saturation: 38, luminance: 10 },
        blending: 55,
        balance: 0,
      },
    },
  },
  {
    id: 'preset-inception-corporate',
    name: 'Inception (Cool Corporate)',
    category: 'Cinematic & Film',
    description: 'Slate blue/grey color grading, desaturated warm tones, sharp structural clarity.',
    adjustments: {
      exposure: 0.05,
      contrast: 26,
      highlights: -25,
      shadows: 12,
      whites: 18,
      blacks: -18,
      temp: 4400,
      tint: -8,
      vibrance: -28,
      saturation: -22,
      clarity: 28,
      texture: 18,
      sharpening: 35,
      vignette: -20,
      colorGrading: {
        shadows: { hue: 215, saturation: 30, luminance: -8 },
        midtones: { hue: 205, saturation: 15, luminance: 0 },
        highlights: { hue: 195, saturation: 20, luminance: 5 },
        blending: 60,
        balance: -12,
      },
    },
  },
  {
    id: 'preset-spiderverse-comic',
    name: 'Spider-Verse (Comic Pop)',
    category: 'Cinematic & Film',
    description: 'High contrast, punchy primary color separation, boosted vibrance, and sharp local texture.',
    adjustments: {
      exposure: 0.1,
      contrast: 45,
      highlights: -10,
      shadows: -15,
      whites: 35,
      blacks: -30,
      temp: 5500,
      tint: 5,
      vibrance: 65,
      saturation: 35,
      clarity: 40,
      texture: 30,
      sharpening: 45,
      vignette: -25,
    },
  },

  // === SUBJECT-FOCUSED PRESETS (8 Presets across subjects) ===
  {
    id: 'preset-subject-soft-skin',
    name: 'Soft Skin Glow',
    category: 'Subject-Focused',
    description: 'Smooth skin tones, subtle warm ambient glow, gentle highlights for portraits.',
    adjustments: {
      exposure: 0.15,
      contrast: -8,
      highlights: -32,
      shadows: 22,
      whites: -12,
      blacks: 12,
      temp: 5800,
      tint: 4,
      vibrance: 14,
      saturation: -4,
      clarity: -20,
      texture: -18,
      sharpening: 22,
    },
  },
  {
    id: 'preset-subject-studio-editorial',
    name: 'Studio Editorial',
    category: 'Subject-Focused',
    description: 'Punchy contrast, crisp highlights, natural skin tones for studio portraits.',
    adjustments: {
      exposure: 0.12,
      contrast: 22,
      highlights: -20,
      shadows: 10,
      whites: 20,
      blacks: -15,
      temp: 5500,
      vibrance: 18,
      saturation: 6,
      clarity: 14,
      texture: 10,
      sharpening: 38,
    },
  },
  {
    id: 'preset-subject-concrete-steel',
    name: 'Concrete & Steel',
    category: 'Subject-Focused',
    description: 'Desaturated warm tones, boosted slate blues, deep blacks for modern architecture.',
    adjustments: {
      exposure: 0.05,
      contrast: 32,
      highlights: -25,
      shadows: 10,
      whites: 15,
      blacks: -25,
      temp: 4800,
      tint: -5,
      vibrance: -25,
      saturation: -20,
      clarity: 28,
      texture: 22,
      dehaze: 15,
    },
  },
  {
    id: 'preset-subject-golden-hour',
    name: 'Golden Hour City',
    category: 'Subject-Focused',
    description: 'Gleaming amber highlights on glass and metal, warm sunset reflections.',
    adjustments: {
      exposure: 0.15,
      contrast: 18,
      highlights: -20,
      shadows: 20,
      whites: 18,
      blacks: -12,
      temp: 6600,
      tint: 10,
      vibrance: 32,
      saturation: 15,
      clarity: 18,
      dehaze: 10,
    },
  },
  {
    id: 'preset-subject-vibrant-feast',
    name: 'Vibrant Feast',
    category: 'Subject-Focused',
    description: 'Boosted warmer food hues, crisp clarity, rich clean whites for culinary photography.',
    adjustments: {
      exposure: 0.18,
      contrast: 24,
      highlights: -15,
      shadows: 18,
      whites: 22,
      blacks: -12,
      temp: 5900,
      tint: 5,
      vibrance: 45,
      saturation: 22,
      clarity: 20,
      texture: 18,
      sharpening: 32,
    },
  },
  {
    id: 'preset-subject-dark-metallic',
    name: 'Dark Metallic Automotive',
    category: 'Subject-Focused',
    description: 'Reflective contrast, desaturated background, punchy metallic bodywork highlights.',
    adjustments: {
      exposure: -0.1,
      contrast: 38,
      highlights: 15,
      shadows: -20,
      whites: 30,
      blacks: -35,
      temp: 5200,
      vibrance: -15,
      saturation: -12,
      clarity: 35,
      texture: 25,
      sharpening: 40,
      vignette: -30,
    },
  },
  {
    id: 'preset-subject-midnight-sky',
    name: 'Midnight Sky Astro',
    category: 'Subject-Focused',
    description: 'Enhanced deep space blues and purples, noise suppression, sharp star point clarity.',
    adjustments: {
      exposure: 0.25,
      contrast: 30,
      highlights: -10,
      shadows: 25,
      whites: 35,
      blacks: -30,
      temp: 4200,
      tint: 18,
      vibrance: 42,
      saturation: 20,
      clarity: 32,
      dehaze: 25,
      sharpening: 45,
    },
  },
  {
    id: 'preset-subject-fur-detail',
    name: 'Fur & Detail Wildlife',
    category: 'Subject-Focused',
    description: 'Boosted texture and micro-clarity, warm organic earth tones for pets and animals.',
    adjustments: {
      exposure: 0.1,
      contrast: 18,
      highlights: -20,
      shadows: 20,
      whites: 15,
      blacks: -12,
      temp: 5700,
      tint: 4,
      vibrance: 22,
      saturation: 10,
      clarity: 25,
      texture: 30,
      sharpening: 42,
    },
  },

  // 1. VINTAGE & ANALOG FILM (10 Presets)
  {
    id: 'preset-portra-400',
    name: 'Portra 400',
    category: 'Vintage & Analog Film',
    description: 'Warm, soft pastel tones, cream highlights, slightly faded blacks.',
    adjustments: {
      exposure: 0.1,
      contrast: -10,
      highlights: -25,
      shadows: 22,
      whites: -15,
      blacks: 18,
      temp: 6100,
      tint: 6,
      vibrance: -8,
      saturation: -5,
      clarity: -6,
      texture: -4,
      sharpening: 12,
      grain: 18,
      vignette: -10,
      colorGrading: {
        shadows: { hue: 35, saturation: 15, luminance: 4 },
        midtones: { hue: 25, saturation: 6, luminance: 0 },
        highlights: { hue: 45, saturation: 12, luminance: 2 },
        blending: 50,
        balance: 5,
      },
    },
  },
  {
    id: 'preset-tri-x-400',
    name: 'Tri-X 400',
    category: 'Vintage & Analog Film',
    description: 'High-contrast classic grain black & white film with deep blacks.',
    adjustments: {
      exposure: 0.15,
      contrast: 38,
      highlights: -18,
      shadows: -15,
      whites: 25,
      blacks: -30,
      temp: 5500,
      vibrance: -100,
      saturation: -100,
      clarity: 25,
      texture: 20,
      sharpening: 35,
      grain: 42,
      vignette: -20,
    },
  },
  {
    id: 'preset-kodachrome-64',
    name: 'Kodachrome 64',
    category: 'Vintage & Analog Film',
    description: 'Punchy reds/yellows, deep contrast, classic mid-century film feel.',
    adjustments: {
      exposure: 0.1,
      contrast: 22,
      highlights: -30,
      shadows: 10,
      whites: 15,
      blacks: -12,
      temp: 5800,
      tint: 4,
      vibrance: 20,
      saturation: 12,
      clarity: 12,
      grain: 15,
      colorGrading: {
        shadows: { hue: 205, saturation: 18, luminance: -5 },
        midtones: { hue: 38, saturation: 12, luminance: 0 },
        highlights: { hue: 42, saturation: 22, luminance: 5 },
        blending: 55,
        balance: 0,
      },
      hsl: {
        ...createDefaultHSLState(),
        red: { hue: -5, saturation: 30, luminance: 5 },
        yellow: { hue: -10, saturation: 25, luminance: 10 },
        green: { hue: -20, saturation: -15, luminance: -5 },
      },
    },
  },
  {
    id: 'preset-fuji-velvia-50',
    name: 'Fuji Velvia 50',
    category: 'Vintage & Analog Film',
    description: 'Ultra-saturated landscapes, intense greens, blues, vivid warm sky.',
    adjustments: {
      exposure: 0.05,
      contrast: 28,
      highlights: -15,
      shadows: 15,
      whites: 20,
      blacks: -18,
      temp: 5600,
      tint: -2,
      vibrance: 45,
      saturation: 25,
      clarity: 18,
      dehaze: 10,
      sharpening: 25,
      hsl: {
        ...createDefaultHSLState(),
        green: { hue: 10, saturation: 40, luminance: 10 },
        blue: { hue: -5, saturation: 35, luminance: 5 },
        yellow: { hue: 5, saturation: 30, luminance: 10 },
      },
    },
  },
  {
    id: 'preset-superia-800',
    name: 'Superia 800',
    category: 'Vintage & Analog Film',
    description: 'Cool green shadows, vibrant primary colors, medium grain.',
    adjustments: {
      exposure: 0.1,
      contrast: 15,
      highlights: -20,
      shadows: 20,
      whites: 10,
      blacks: 12,
      temp: 5200,
      tint: -8,
      vibrance: 12,
      saturation: 5,
      grain: 32,
      colorGrading: {
        shadows: { hue: 165, saturation: 20, luminance: 0 },
        midtones: { hue: 30, saturation: 8, luminance: 0 },
        highlights: { hue: 50, saturation: 15, luminance: 5 },
        blending: 50,
        balance: -8,
      },
    },
  },
  {
    id: 'preset-ektar-100',
    name: 'Ektar 100',
    category: 'Vintage & Analog Film',
    description: 'Fine grain, vivid ultra-clean contrast, saturated primary tones.',
    adjustments: {
      exposure: 0.15,
      contrast: 32,
      highlights: -10,
      shadows: 12,
      whites: 22,
      blacks: -15,
      temp: 5700,
      vibrance: 30,
      saturation: 18,
      clarity: 15,
      sharpening: 30,
      grain: 8,
    },
  },
  {
    id: 'preset-instant-polaroid',
    name: 'Instant Polaroid',
    category: 'Vintage & Analog Film',
    description: 'Faded washed shadows, warm greenish tint, soft low contrast.',
    adjustments: {
      exposure: 0.2,
      contrast: -18,
      highlights: -35,
      shadows: 35,
      whites: -25,
      blacks: 40,
      temp: 6400,
      tint: 10,
      vibrance: -15,
      saturation: -18,
      clarity: -12,
      grain: 30,
      vignette: -22,
    },
  },
  {
    id: 'preset-expired-film',
    name: 'Expired Film',
    category: 'Vintage & Analog Film',
    description: 'Shifted cyan/magenta hues, heavy grain, faded contrast, retro tint.',
    adjustments: {
      exposure: 0.05,
      contrast: -10,
      highlights: -30,
      shadows: 30,
      whites: -15,
      blacks: 25,
      temp: 4800,
      tint: 22,
      vibrance: -22,
      saturation: -15,
      grain: 48,
      vignette: -28,
    },
  },
  {
    id: 'preset-agfa-vista-200',
    name: 'Agfa Vista 200',
    category: 'Vintage & Analog Film',
    description: 'Bright warm yellows, punchy red tones, airy summer film look.',
    adjustments: {
      exposure: 0.25,
      contrast: 12,
      highlights: -15,
      shadows: 18,
      whites: 15,
      blacks: 5,
      temp: 6000,
      tint: 2,
      vibrance: 22,
      saturation: 10,
      grain: 16,
    },
  },
  {
    id: 'preset-cinestill-800t',
    name: 'CineStill 800T',
    category: 'Vintage & Analog Film',
    description: 'Tungsten color balance, halation warmth, rich blue/teal dark shadows.',
    adjustments: {
      exposure: 0.1,
      contrast: 25,
      highlights: -25,
      shadows: 15,
      whites: 20,
      blacks: -10,
      temp: 3800,
      tint: -15,
      vibrance: 25,
      saturation: 10,
      grain: 28,
      colorGrading: {
        shadows: { hue: 210, saturation: 30, luminance: -8 },
        midtones: { hue: 25, saturation: 12, luminance: 0 },
        highlights: { hue: 20, saturation: 35, luminance: 10 },
        blending: 60,
        balance: -12,
      },
    },
  },

  // 2. MODERN CINEMATIC TONES (10 Presets)
  {
    id: 'preset-moody-teal-orange',
    name: 'Moody Teal & Orange',
    category: 'Modern Cinematic Tones',
    description: 'Blockbuster movie aesthetic with orange skin tones & teal shadows.',
    adjustments: {
      exposure: 0.05,
      contrast: 22,
      highlights: -30,
      shadows: 15,
      whites: 15,
      blacks: -20,
      temp: 5800,
      tint: -2,
      vibrance: 18,
      saturation: -5,
      clarity: 15,
      vignette: -20,
      colorGrading: {
        shadows: { hue: 200, saturation: 38, luminance: -8 },
        midtones: { hue: 32, saturation: 20, luminance: 0 },
        highlights: { hue: 42, saturation: 32, luminance: 8 },
        blending: 60,
        balance: -5,
      },
    },
  },
  {
    id: 'preset-cyberpunk-neon',
    name: 'Cyberpunk Neon',
    category: 'Modern Cinematic Tones',
    description: 'Cool blues/magentas, bright neon highlights, dark atmospheric shadows.',
    adjustments: {
      exposure: 0.1,
      contrast: 32,
      highlights: -20,
      shadows: 20,
      whites: 25,
      blacks: -22,
      temp: 4200,
      tint: -25,
      vibrance: 45,
      saturation: 22,
      clarity: 28,
      vignette: -32,
      colorGrading: {
        shadows: { hue: 280, saturation: 42, luminance: -12 },
        midtones: { hue: 320, saturation: 25, luminance: 0 },
        highlights: { hue: 185, saturation: 48, luminance: 10 },
        blending: 65,
        balance: -10,
      },
    },
  },
  {
    id: 'preset-golden-hour-glow',
    name: 'Golden Hour Glow',
    category: 'Modern Cinematic Tones',
    description: 'Sun-drenched, amber hues, creamy highlights, warm shadows.',
    adjustments: {
      exposure: 0.15,
      contrast: -5,
      highlights: -35,
      shadows: 25,
      whites: -10,
      blacks: 12,
      temp: 6800,
      tint: 12,
      vibrance: 22,
      saturation: 8,
      clarity: -8,
      vignette: -12,
      colorGrading: {
        shadows: { hue: 38, saturation: 22, luminance: 5 },
        midtones: { hue: 45, saturation: 15, luminance: 0 },
        highlights: { hue: 50, saturation: 30, luminance: 10 },
        blending: 50,
        balance: 10,
      },
    },
  },
  {
    id: 'preset-bleach-bypass',
    name: 'Bleach Bypass',
    category: 'Modern Cinematic Tones',
    description: 'Desaturated colors with high-contrast silvery metallic movie look.',
    adjustments: {
      exposure: 0.05,
      contrast: 45,
      highlights: -15,
      shadows: -20,
      whites: 30,
      blacks: -35,
      temp: 5400,
      vibrance: -65,
      saturation: -50,
      clarity: 35,
      texture: 25,
      sharpening: 30,
      vignette: -25,
    },
  },
  {
    id: 'preset-cold-nordics',
    name: 'Cold Nordics',
    category: 'Modern Cinematic Tones',
    description: 'Icy blue midtones, muted greens, clean desaturated aesthetic.',
    adjustments: {
      exposure: 0.05,
      contrast: 12,
      highlights: -25,
      shadows: 20,
      whites: 10,
      blacks: -10,
      temp: 4500,
      tint: -10,
      vibrance: -25,
      saturation: -20,
      clarity: 10,
      colorGrading: {
        shadows: { hue: 215, saturation: 25, luminance: -5 },
        midtones: { hue: 205, saturation: 12, luminance: 0 },
        highlights: { hue: 195, saturation: 18, luminance: 5 },
        blending: 55,
        balance: -15,
      },
    },
  },
  {
    id: 'preset-matte-noir',
    name: 'Matte Noir',
    category: 'Modern Cinematic Tones',
    description: 'Deep crushed matte shadows, subtle warm highlights, moody contrast.',
    adjustments: {
      exposure: -0.2,
      contrast: 25,
      highlights: -40,
      shadows: -15,
      whites: -10,
      blacks: 30,
      temp: 5700,
      vibrance: -30,
      saturation: -25,
      clarity: 15,
      vignette: -30,
      grain: 15,
    },
  },
  {
    id: 'preset-emerald-shadow',
    name: 'Emerald Shadow',
    category: 'Modern Cinematic Tones',
    description: 'Rich emerald green shadow tint paired with warm golden highlights.',
    adjustments: {
      exposure: 0.0,
      contrast: 20,
      highlights: -20,
      shadows: 15,
      whites: 12,
      blacks: -18,
      temp: 5600,
      tint: -12,
      vibrance: 15,
      saturation: -8,
      colorGrading: {
        shadows: { hue: 155, saturation: 32, luminance: -5 },
        midtones: { hue: 35, saturation: 10, luminance: 0 },
        highlights: { hue: 45, saturation: 25, luminance: 8 },
        blending: 55,
        balance: -10,
      },
    },
  },
  {
    id: 'preset-sunset-crimson',
    name: 'Sunset Crimson',
    category: 'Modern Cinematic Tones',
    description: 'Deep crimson red/violet sky, warm golden midtones, high dramatic contrast.',
    adjustments: {
      exposure: 0.1,
      contrast: 28,
      highlights: -25,
      shadows: 10,
      whites: 20,
      blacks: -20,
      temp: 6500,
      tint: 25,
      vibrance: 35,
      saturation: 15,
      clarity: 18,
      vignette: -25,
    },
  },
  {
    id: 'preset-matrix-green',
    name: 'Matrix Green',
    category: 'Modern Cinematic Tones',
    description: 'Atmospheric sci-fi green tint, deep contrast, desaturated primaries.',
    adjustments: {
      exposure: -0.1,
      contrast: 30,
      highlights: -30,
      shadows: -10,
      whites: 10,
      blacks: -25,
      temp: 5000,
      tint: -35,
      vibrance: -30,
      saturation: -25,
      clarity: 22,
      vignette: -35,
    },
  },
  {
    id: 'preset-vintage-cinema',
    name: 'Vintage Cinema',
    category: 'Modern Cinematic Tones',
    description: 'Warm sepia/amber highlights, cool slate shadows, smooth film compression.',
    adjustments: {
      exposure: 0.05,
      contrast: 10,
      highlights: -35,
      shadows: 25,
      whites: -15,
      blacks: 18,
      temp: 6200,
      tint: 5,
      vibrance: -15,
      saturation: -10,
      grain: 20,
    },
  },

  // 3. PORTRAIT & SKIN RETOUCHING (8 Presets)
  {
    id: 'preset-soft-skin-glow',
    name: 'Soft Skin Glow',
    category: 'Portrait & Skin Retouching',
    description: 'Gentle highlight softening, warm skin tones, smoothed micro-textures.',
    adjustments: {
      exposure: 0.15,
      contrast: -8,
      highlights: -30,
      shadows: 20,
      whites: -10,
      blacks: 10,
      temp: 5800,
      tint: 4,
      vibrance: 12,
      saturation: -4,
      clarity: -18,
      texture: -15,
      sharpening: 20,
      vignette: -12,
    },
  },
  {
    id: 'preset-studio-portrait',
    name: 'Studio Portrait',
    category: 'Portrait & Skin Retouching',
    description: 'Clean neutral color balance, crisp detail, rich natural skin pop.',
    adjustments: {
      exposure: 0.1,
      contrast: 15,
      highlights: -18,
      shadows: 12,
      whites: 15,
      blacks: -10,
      temp: 5500,
      tint: 0,
      vibrance: 15,
      saturation: 5,
      clarity: 8,
      texture: 5,
      sharpening: 35,
    },
  },
  {
    id: 'preset-clean-commercial',
    name: 'Clean Commercial',
    category: 'Portrait & Skin Retouching',
    description: 'Bright, high-clarity, true-to-life tones with soft fills.',
    adjustments: {
      exposure: 0.25,
      contrast: 10,
      highlights: -20,
      shadows: 25,
      whites: 20,
      blacks: -5,
      temp: 5400,
      tint: 0,
      vibrance: 18,
      saturation: 8,
      clarity: 10,
      dehaze: 5,
      sharpening: 30,
    },
  },
  {
    id: 'preset-editorial-high-key',
    name: 'Editorial High-Key',
    category: 'Portrait & Skin Retouching',
    description: 'Bright ethereal highlights, low contrast, soft pastel skin tones.',
    adjustments: {
      exposure: 0.45,
      contrast: -15,
      highlights: -40,
      shadows: 35,
      whites: 10,
      blacks: 25,
      temp: 5600,
      tint: 2,
      vibrance: -12,
      saturation: -15,
      clarity: -12,
      texture: -8,
    },
  },
  {
    id: 'preset-warm-honey',
    name: 'Warm Honey',
    category: 'Portrait & Skin Retouching',
    description: 'Golden honey skin glow, soft shadows, warm ambient light.',
    adjustments: {
      exposure: 0.15,
      contrast: -5,
      highlights: -25,
      shadows: 18,
      whites: -5,
      blacks: 10,
      temp: 6400,
      tint: 8,
      vibrance: 20,
      saturation: 5,
      clarity: -10,
      vignette: -15,
    },
  },
  {
    id: 'preset-cool-porcelain',
    name: 'Cool Porcelain',
    category: 'Portrait & Skin Retouching',
    description: 'Fair, porcelain skin tones, cool desaturated background, sharp contrast.',
    adjustments: {
      exposure: 0.1,
      contrast: 18,
      highlights: -20,
      shadows: 10,
      whites: 15,
      blacks: -12,
      temp: 4800,
      tint: -5,
      vibrance: -18,
      saturation: -15,
      sharpening: 28,
    },
  },
  {
    id: 'preset-glamour-warmth',
    name: 'Glamour Warmth',
    category: 'Portrait & Skin Retouching',
    description: 'Rich warm highlights, lifted shadows, gentle vignette focus.',
    adjustments: {
      exposure: 0.2,
      contrast: 8,
      highlights: -22,
      shadows: 22,
      whites: 12,
      blacks: 8,
      temp: 6200,
      tint: 6,
      vibrance: 15,
      clarity: -8,
      vignette: -18,
    },
  },
  {
    id: 'preset-soft-velvet',
    name: 'Soft Velvet',
    category: 'Portrait & Skin Retouching',
    description: 'Smooth velvety skin tones, reduced texture, elegant pastel atmosphere.',
    adjustments: {
      exposure: 0.1,
      contrast: -12,
      highlights: -35,
      shadows: 30,
      whites: -15,
      blacks: 20,
      temp: 5700,
      tint: 3,
      vibrance: -10,
      clarity: -20,
      texture: -18,
    },
  },

  // 4. NATURE & LANDSCAPE (10 Presets)
  {
    id: 'preset-forest-greens',
    name: 'Forest Greens',
    category: 'Nature & Landscape',
    description: 'Rich desaturated forest greens, deep earthy brown shadows.',
    adjustments: {
      exposure: 0.05,
      contrast: 20,
      highlights: -30,
      shadows: 18,
      whites: 10,
      blacks: -18,
      temp: 5300,
      tint: -10,
      vibrance: 15,
      saturation: -10,
      clarity: 18,
      dehaze: 12,
      hsl: {
        ...createDefaultHSLState(),
        green: { hue: -15, saturation: -25, luminance: -15 },
        yellow: { hue: -10, saturation: -15, luminance: -5 },
      },
    },
  },
  {
    id: 'preset-deep-ocean-blue',
    name: 'Deep Ocean Blue',
    category: 'Nature & Landscape',
    description: 'Vivid deep blue waters, crisp whites, dehazed atmospheric sky.',
    adjustments: {
      exposure: 0.1,
      contrast: 25,
      highlights: -25,
      shadows: 15,
      whites: 20,
      blacks: -15,
      temp: 4600,
      tint: -8,
      vibrance: 35,
      saturation: 15,
      clarity: 22,
      dehaze: 20,
      hsl: {
        ...createDefaultHSLState(),
        blue: { hue: 0, saturation: 40, luminance: -10 },
        aqua: { hue: -5, saturation: 35, luminance: 5 },
      },
    },
  },
  {
    id: 'preset-desert-dust',
    name: 'Desert Dust',
    category: 'Nature & Landscape',
    description: 'Warm sandy tones, muted sky blues, golden shadow glow.',
    adjustments: {
      exposure: 0.15,
      contrast: 10,
      highlights: -20,
      shadows: 22,
      whites: 15,
      blacks: -10,
      temp: 6600,
      tint: 14,
      vibrance: 18,
      saturation: 5,
      clarity: 12,
    },
  },
  {
    id: 'preset-moody-mist',
    name: 'Moody Mist',
    category: 'Nature & Landscape',
    description: 'Low-contrast fog, cool desaturated greens, soft ethereal whites.',
    adjustments: {
      exposure: 0.1,
      contrast: -15,
      highlights: -40,
      shadows: 35,
      whites: -20,
      blacks: 25,
      temp: 5000,
      tint: -5,
      vibrance: -25,
      saturation: -20,
      clarity: -12,
      dehaze: -15,
    },
  },
  {
    id: 'preset-autumn-foliage',
    name: 'Autumn Foliage',
    category: 'Nature & Landscape',
    description: 'Vivid oranges, rich reds, warm golden yellows, rich contrast.',
    adjustments: {
      exposure: 0.1,
      contrast: 25,
      highlights: -20,
      shadows: 15,
      whites: 18,
      blacks: -12,
      temp: 6300,
      tint: 10,
      vibrance: 40,
      saturation: 20,
      clarity: 18,
      hsl: {
        ...createDefaultHSLState(),
        red: { hue: 5, saturation: 35, luminance: 5 },
        orange: { hue: -5, saturation: 40, luminance: 10 },
        yellow: { hue: -15, saturation: 35, luminance: 5 },
        green: { hue: -25, saturation: -30, luminance: -10 },
      },
    },
  },
  {
    id: 'preset-snow-alpine',
    name: 'Snow & Alpine',
    category: 'Nature & Landscape',
    description: 'Crisp cool snow whites, deep blue mountain shadows, high clarity.',
    adjustments: {
      exposure: 0.25,
      contrast: 22,
      highlights: -35,
      shadows: 20,
      whites: 30,
      blacks: -15,
      temp: 4800,
      tint: -5,
      vibrance: 15,
      saturation: -5,
      clarity: 25,
      dehaze: 15,
    },
  },
  {
    id: 'preset-tropical-pop',
    name: 'Tropical Pop',
    category: 'Nature & Landscape',
    description: 'Vivid turquoise waters, lush palm greens, sunny warm exposure.',
    adjustments: {
      exposure: 0.2,
      contrast: 20,
      highlights: -15,
      shadows: 18,
      whites: 22,
      blacks: -10,
      temp: 5800,
      tint: -4,
      vibrance: 45,
      saturation: 22,
      clarity: 20,
      dehaze: 10,
    },
  },
  {
    id: 'preset-sunset-drama',
    name: 'Sunset Drama',
    category: 'Nature & Landscape',
    description: 'Punchy warm sunset hues, deep shadow silhouettes, vivid sky saturation.',
    adjustments: {
      exposure: -0.1,
      contrast: 35,
      highlights: -45,
      shadows: -20,
      whites: 20,
      blacks: -35,
      temp: 6700,
      tint: 20,
      vibrance: 45,
      saturation: 25,
      clarity: 25,
      dehaze: 18,
      vignette: -25,
    },
  },
  {
    id: 'preset-mountain-dawn',
    name: 'Mountain Dawn',
    category: 'Nature & Landscape',
    description: 'Cool purple/blue morning haze with warm rising golden highlights.',
    adjustments: {
      exposure: 0.1,
      contrast: 15,
      highlights: -25,
      shadows: 20,
      whites: 12,
      blacks: -10,
      temp: 5200,
      tint: 12,
      vibrance: 25,
      saturation: 10,
      clarity: 15,
    },
  },
  {
    id: 'preset-golden-savanna',
    name: 'Golden Savanna',
    category: 'Nature & Landscape',
    description: 'Warm amber grasses, rich earth tones, high-contrast cloud clarity.',
    adjustments: {
      exposure: 0.15,
      contrast: 22,
      highlights: -20,
      shadows: 15,
      whites: 18,
      blacks: -15,
      temp: 6500,
      tint: 8,
      vibrance: 30,
      saturation: 12,
      clarity: 20,
    },
  },

  // 5. B&W FINE ART (8 Presets)
  {
    id: 'preset-high-contrast-drama',
    name: 'High Contrast Drama',
    category: 'B&W Fine Art',
    description: 'Punchy monochrome, extreme whites, pitch dark blacks.',
    adjustments: {
      exposure: 0.1,
      contrast: 48,
      highlights: -15,
      shadows: -25,
      whites: 35,
      blacks: -40,
      vibrance: -100,
      saturation: -100,
      clarity: 38,
      texture: 28,
      dehaze: 20,
      sharpening: 40,
      vignette: -25,
    },
  },
  {
    id: 'preset-soft-silver-tones',
    name: 'Soft Silver Tones',
    category: 'B&W Fine Art',
    description: 'Smooth silver gradations, delicate highlights, gentle shadows.',
    adjustments: {
      exposure: 0.15,
      contrast: -8,
      highlights: -35,
      shadows: 30,
      whites: -10,
      blacks: 15,
      vibrance: -100,
      saturation: -100,
      clarity: -8,
      texture: -5,
      sharpening: 15,
    },
  },
  {
    id: 'preset-deep-shadow-noir',
    name: 'Deep Shadow Noir',
    category: 'B&W Fine Art',
    description: 'Moody low-key black and white, crushed blacks, subtle light accents.',
    adjustments: {
      exposure: -0.3,
      contrast: 35,
      highlights: -20,
      shadows: -30,
      whites: 20,
      blacks: -45,
      vibrance: -100,
      saturation: -100,
      clarity: 25,
      vignette: -40,
      grain: 20,
    },
  },
  {
    id: 'preset-infrared-bw',
    name: 'Infrared B&W',
    category: 'B&W Fine Art',
    description: 'Glowing white foliage, pitch black sky, extreme tonal inversion.',
    adjustments: {
      exposure: 0.2,
      contrast: 40,
      highlights: 30,
      shadows: -35,
      whites: 45,
      blacks: -40,
      vibrance: -100,
      saturation: -100,
      clarity: 35,
      dehaze: 25,
      sharpening: 35,
    },
  },
  {
    id: 'preset-sepia-antique',
    name: 'Sepia Antique',
    category: 'B&W Fine Art',
    description: 'Rich warm amber sepia tone, aged paper contrast, subtle grain.',
    adjustments: {
      exposure: 0.1,
      contrast: 10,
      highlights: -25,
      shadows: 20,
      whites: -15,
      blacks: 15,
      vibrance: -100,
      saturation: -100,
      grain: 32,
      vignette: -20,
      colorGrading: {
        shadows: { hue: 35, saturation: 28, luminance: 0 },
        midtones: { hue: 40, saturation: 20, luminance: 0 },
        highlights: { hue: 45, saturation: 35, luminance: 5 },
        blending: 50,
        balance: 10,
      },
    },
  },
  {
    id: 'preset-platinum-print',
    name: 'Platinum Print',
    category: 'B&W Fine Art',
    description: 'Luminous metallic tonal range, warm platinum highlights, deep gray blacks.',
    adjustments: {
      exposure: 0.15,
      contrast: 18,
      highlights: -20,
      shadows: 25,
      whites: 15,
      blacks: -10,
      vibrance: -100,
      saturation: -100,
      clarity: 12,
      colorGrading: {
        shadows: { hue: 210, saturation: 8, luminance: -5 },
        midtones: { hue: 40, saturation: 10, luminance: 0 },
        highlights: { hue: 45, saturation: 18, luminance: 5 },
        blending: 50,
        balance: 0,
      },
    },
  },
  {
    id: 'preset-ansel-zone-system',
    name: 'Ansel Zone System',
    category: 'B&W Fine Art',
    description: 'Full-range 10-zone tonal gradation from Zone 0 pitch black to Zone X white.',
    adjustments: {
      exposure: 0.05,
      contrast: 28,
      highlights: -15,
      shadows: 15,
      whites: 22,
      blacks: -22,
      vibrance: -100,
      saturation: -100,
      clarity: 28,
      sharpening: 30,
    },
  },
  {
    id: 'preset-split-tone-monolith',
    name: 'Split-Tone Monolith',
    category: 'B&W Fine Art',
    description: 'Warm highlight split-tone over cool slate black-and-white base.',
    adjustments: {
      exposure: 0.1,
      contrast: 25,
      highlights: -25,
      shadows: 10,
      whites: 15,
      blacks: -18,
      vibrance: -100,
      saturation: -100,
      colorGrading: {
        shadows: { hue: 215, saturation: 25, luminance: -8 },
        midtones: { hue: 0, saturation: 0, luminance: 0 },
        highlights: { hue: 42, saturation: 30, luminance: 8 },
        blending: 55,
        balance: 0,
      },
    },
  },

  // 6. SOCIAL & LIFESTYLE (8 Presets)
  {
    id: 'preset-minimalist-beige',
    name: 'Minimalist Beige',
    category: 'Social & Lifestyle',
    description: 'Warm neutral beige pastels, low saturation, clean aesthetic.',
    adjustments: {
      exposure: 0.2,
      contrast: -10,
      highlights: -35,
      shadows: 30,
      whites: -15,
      blacks: 22,
      temp: 6200,
      tint: 6,
      vibrance: -20,
      saturation: -18,
      clarity: -10,
      texture: -5,
    },
  },
  {
    id: 'preset-clean-aesthetic',
    name: 'Clean Aesthetic',
    category: 'Social & Lifestyle',
    description: 'Crisp bright whites, neutral skin tones, subtle contrast.',
    adjustments: {
      exposure: 0.25,
      contrast: 5,
      highlights: -25,
      shadows: 20,
      whites: 25,
      blacks: -5,
      temp: 5400,
      tint: 0,
      vibrance: -5,
      saturation: -5,
      clarity: 8,
      sharpening: 25,
    },
  },
  {
    id: 'preset-vibrant-food',
    name: 'Vibrant Food',
    category: 'Social & Lifestyle',
    description: 'Warm appetizing highlights, punchy reds & yellows, high saturation.',
    adjustments: {
      exposure: 0.15,
      contrast: 22,
      highlights: -15,
      shadows: 18,
      whites: 20,
      blacks: -10,
      temp: 5800,
      tint: 4,
      vibrance: 40,
      saturation: 20,
      clarity: 18,
      texture: 15,
      sharpening: 30,
    },
  },
  {
    id: 'preset-street-urban',
    name: 'Street Urban',
    category: 'Social & Lifestyle',
    description: 'Gritty urban contrast, desaturated greens, punchy asphalt blues.',
    adjustments: {
      exposure: 0.05,
      contrast: 28,
      highlights: -25,
      shadows: 12,
      whites: 15,
      blacks: -22,
      temp: 5100,
      tint: -4,
      vibrance: -15,
      saturation: -10,
      clarity: 25,
      texture: 20,
      vignette: -20,
    },
  },
  {
    id: 'preset-pastel-dream',
    name: 'Pastel Dream',
    category: 'Social & Lifestyle',
    description: 'Dreamy pink & cyan pastels, soft focus texture, airy exposure.',
    adjustments: {
      exposure: 0.3,
      contrast: -15,
      highlights: -40,
      shadows: 35,
      whites: -10,
      blacks: 25,
      temp: 5600,
      tint: 15,
      vibrance: 10,
      saturation: -10,
      clarity: -18,
      texture: -12,
    },
  },
  {
    id: 'preset-dark-aesthetic',
    name: 'Dark Aesthetic',
    category: 'Social & Lifestyle',
    description: 'Moody dark feed style, crushed shadows, desaturated background.',
    adjustments: {
      exposure: -0.25,
      contrast: 20,
      highlights: -35,
      shadows: -15,
      whites: 10,
      blacks: -28,
      temp: 5600,
      vibrance: -35,
      saturation: -25,
      clarity: 12,
      vignette: -28,
    },
  },
  {
    id: 'preset-warm-coffee',
    name: 'Warm Coffee',
    category: 'Social & Lifestyle',
    description: 'Deep espresso shadows, warm latte highlights, cozy interior mood.',
    adjustments: {
      exposure: 0.1,
      contrast: -2,
      highlights: -30,
      shadows: 25,
      whites: -10,
      blacks: 15,
      temp: 6500,
      tint: 10,
      vibrance: 12,
      saturation: -5,
      vignette: -15,
    },
  },
  {
    id: 'preset-minimalist-slate',
    name: 'Minimalist Slate',
    category: 'Social & Lifestyle',
    description: 'Cool slate grays, desaturated background, subtle contrast.',
    adjustments: {
      exposure: 0.1,
      contrast: 8,
      highlights: -25,
      shadows: 18,
      whites: 10,
      blacks: -8,
      temp: 4900,
      tint: -6,
      vibrance: -30,
      saturation: -25,
      clarity: 10,
    },
  },
];
